#!/usr/bin/env bash

# Robert 'Bobby' Zenz
# https://github.com/RobertZenz/BobbysBashDir
# Licensed as Public Domain or Creative Commons Zero


__exit_norm=0			# Normal completion
__exit_ok=0				# Normal completion
__exit_perm=1 			# Operation not permitted
__exit_general=1 		# General error
__exit_noent=2 			# No such file or directory
__exit_misuse=2			# Misuse of shell builtins
__exit_srch=3 			# No such process
__exit_intr=4 			# Interrupted system call
__exit_io=5 			# I/O error
__exit_nxio=6 			# No such device or address
__exit_2big=7 			# Argument list too long
__exit_noexec=8 		# Exec format error
__exit_badf=9 			# Bad file number
__exit_child=10 		# No child processes
__exit_again=11 		# Try again
__exit_nomem=12 		# Out of memory
__exit_acces=13 		# Permission denied
__exit_fault=14 		# Bad address
__exit_notblk=15 		# Block device required
__exit_busy=16 			# Device or resource busy
__exit_exist=17 		# File exists
__exit_xdev=18 			# Cross-device link
__exit_nodev=19 		# No such device
__exit_notdir=20 		# Not a directory
__exit_isdir=21 		# Is a directory
__exit_inval=22 		# Invalid argument
__exit_nfile=23 		# File table overflow
__exit_mfile=24 		# Too many open files
__exit_notty=25 		# Not a typewriter
__exit_txtbsy=26 		# Text file busy
__exit_fbig=27 			# File too large
__exit_nospc=28 		# No space left on device
__exit_spipe=29 		# Illegal seek
__exit_rofs=30 			# Read-only file system
__exit_mlink=31 		# Too many links
__exit_pipe=32 			# Broken pipe
__exit_dom=33 			# Math argument out of domain of func
__exit_range=34 		# Math result not representable
__exit_deadlk=35 		# Resource deadlock would occur
__exit_nametoolong=36 	# File name too long
__exit_nolck=37 		# No record locks available
__exit_nosys=38 		# Function not implemented
__exit_notempty=39	 	# Directory not empty
__exit_loop=40 			# Too many symbolic links encountered
__exit_wouldblock=$__exit_again	# Operation would block
__exit_nomsg=42 		# No message of desired type
__exit_idrm=43 			# Identifier removed
__exit_chrng=44 		# Channel number out of range
__exit_l2nsync=45 		# Level 2 not synchronized
__exit_l3hlt=46 		# Level 3 halted
__exit_l3rst=47 		# Level 3 reset
__exit_lnrng=48 		# Link number out of range
__exit_unatch=49 		# Protocol driver not attached
__exit_nocsi=50 		# No CSI structure available
__exit_l2hlt=51 		# Level 2 halted
__exit_bade=52 			# Invalid exchange
__exit_badr=53 			# Invalid request descriptor
__exit_xfull=54 		# Exchange full
__exit_noano=55 		# No anode
__exit_badrqc=56 		# Invalid request code
__exit_badslt=57 		# Invalid slot
__exit_deadlock=$__exit_deadlk
__exit_bfont=59 		# Bad font file format
__exit_nostr=60 		# Device not a stream
__exit_nodata=61 		# No data available
__exit_time=62 			# Timer expired
__exit_nosr=63 			# Out of streams resources
__exit_nonet=64 		# Machine is not on the network
__exit_nopkg=65 		# Package not installed
__exit_remote=66 		# Object is remote
__exit_nolink=67 		# Link has been severed
__exit_adv=68 			# Advertise error
__exit_srmnt=69 		# Srmount error
__exit_comm=70 			# Communication error on send
__exit_proto=71 		# Protocol error
__exit_multihop=72 		# Multihop attempted
__exit_dotdot=73 		# RFS specific error
__exit_badmsg=74 		# Not a data message
__exit_overflow=75 		# Value too large for defined data type
__exit_notuniq=76 		# Name not unique on network
__exit_badfd=77 		# File descriptor in bad state
__exit_remchg=78 		# Remote address changed
__exit_libacc=79 		# Can not access a needed shared library
__exit_libbad=80 		# Accessing a corrupted shared library
__exit_libscn=81 		# .lib section in a.out corrupted
__exit_libmax=82 		# Attempting to link in too many shared libraries
__exit_libexec=83 		# Cannot exec a shared library directly
__exit_ilseq=84 		# Illegal byte sequence
__exit_restart=85 		# Interrupted system call should be restarted
__exit_strpipe=86 		# Streams pipe error
__exit_users=87 		# Too many users
__exit_notsock=88 		# Socket operation on non-socket
__exit_destaddrreq=89 	# Destination address required
__exit_msgsize=90 		# Message too long
__exit_prototype=91 	# Protocol wrong type for socket
__exit_noprotoopt=92 	# Protocol not available
__exit_protonosupport=93	# Protocol not supported
__exit_socktnosupport=94	# Socket type not supported
__exit_opnotsupp=95 	# Operation not supported on transport endpoint
__exit_pfnosupport=96 	# Protocol family not supported
__exit_afnosupport=97 	# Address family not supported by protocol
__exit_addrinuse=98 	# Address already in use
__exit_addrnotavail=99 	# Cannot assign requested address
__exit_netdown=100		# Network is down
__exit_netunreach=101	# Network is unreachable
__exit_netreset=102		# Network dropped connection because of reset
__exit_connaborted=103	# Software caused connection abort
__exit_connreset=104	# Connection reset by peer
__exit_nobufs=105		# No buffer space available
__exit_isconn=106		# Transport endpoint is already connected
__exit_notconn=107		# Transport endpoint is not connected
__exit_shutdown=108		# Cannot send after transport endpoint shutdown
__exit_toomanyrefs=109	# Too many references: cannot splice
__exit_timedout=110		# Connection timed out
__exit_connrefused=111	# Connection refused
__exit_hostdown=112		# Host is down
__exit_hostunreach=113	# No route to host
__exit_already=114		# Operation already in progress
__exit_inprogress=115	# Operation now in progress
__exit_stale=116		# Stale NFS file handle
__exit_uclean=117		# Structure needs cleaning
__exit_notnam=118		# Not a XENIX named type file
__exit_navail=119		# No XENIX semaphores available
__exit_isnam=120		# Is a named type file
__exit_remoteio=121		# Remote I/O error
__exit_dquot=122		# Quota exceeded
__exit_nomedium=123		# No medium found
__exit_mediumtype=124	# Wrong medium type
__exit_canceled=125		# Operation Canceled
__exit_nokey=126		# Required key not available
__exit_comexe=126		# Command invoked cannot execute
__exit_keyexpired=127	# Key has expired
__exit_nocommmand=127	# Command not found
__exit_keyrevoked=128	# Key has been revoked
__exit_invalexit=128	# Invalid argument to exit
__exit_keyrejected=129	# Key was rejected by service


__exit_codes=()
__exit_codes[0]="norm|ok"
__exit_codes[1]="perm|general"
__exit_codes[2]="noent|misuse"
__exit_codes[3]="srch"
__exit_codes[4]="intr"
__exit_codes[5]="io"
__exit_codes[6]="nxio"
__exit_codes[7]="2big"
__exit_codes[8]="noexec"
__exit_codes[9]="badf"
__exit_codes[10]="child"
__exit_codes[11]="again"
__exit_codes[12]="nomem"
__exit_codes[13]="acces"
__exit_codes[14]="fault"
__exit_codes[15]="notblk"
__exit_codes[16]="busy"
__exit_codes[17]="exist"
__exit_codes[18]="xdev"
__exit_codes[19]="nodev"
__exit_codes[20]="notdir"
__exit_codes[21]="isdir"
__exit_codes[22]="inval"
__exit_codes[23]="nfile"
__exit_codes[24]="mfile"
__exit_codes[25]="notty"
__exit_codes[26]="txtbsy"
__exit_codes[27]="fbig"
__exit_codes[28]="nospc"
__exit_codes[29]="spipe"
__exit_codes[30]="rofs"
__exit_codes[31]="mlink"
__exit_codes[32]="pipe"
__exit_codes[33]="dom"
__exit_codes[34]="range"
__exit_codes[35]="deadlk"
__exit_codes[36]="nametoolong"
__exit_codes[37]="nolck"
__exit_codes[38]="nosys"
__exit_codes[39]="notempty"
__exit_codes[40]="loop"
__exit_codes[41]="wouldblock"
__exit_codes[42]="nomsg"
__exit_codes[43]="idrm"
__exit_codes[44]="chrng"
__exit_codes[45]="l2nsync"
__exit_codes[46]="l3hlt"
__exit_codes[47]="l3rst"
__exit_codes[48]="lnrng"
__exit_codes[49]="unatch"
__exit_codes[50]="nocsi"
__exit_codes[51]="l2hlt"
__exit_codes[52]="bade"
__exit_codes[53]="badr"
__exit_codes[54]="xfull"
__exit_codes[55]="noano"
__exit_codes[56]="badrqc"
__exit_codes[57]="badslt"
__exit_codes[41]="deadlock"
__exit_codes[59]="bfont"
__exit_codes[60]="nostr"
__exit_codes[61]="nodata"
__exit_codes[62]="time"
__exit_codes[63]="nosr"
__exit_codes[64]="nonet"
__exit_codes[65]="nopkg"
__exit_codes[66]="remote"
__exit_codes[67]="nolink"
__exit_codes[68]="adv"
__exit_codes[69]="srmnt"
__exit_codes[70]="comm"
__exit_codes[71]="proto"
__exit_codes[72]="multihop"
__exit_codes[73]="dotdot"
__exit_codes[74]="badmsg"
__exit_codes[75]="overflow"
__exit_codes[76]="notuniq"
__exit_codes[77]="badfd"
__exit_codes[78]="remchg"
__exit_codes[79]="libacc"
__exit_codes[80]="libbad"
__exit_codes[81]="libscn"
__exit_codes[82]="libmax"
__exit_codes[83]="libexec"
__exit_codes[84]="ilseq"
__exit_codes[85]="restart"
__exit_codes[86]="strpipe"
__exit_codes[87]="users"
__exit_codes[88]="notsock"
__exit_codes[89]="destaddrreq"
__exit_codes[90]="msgsize"
__exit_codes[91]="prototype"
__exit_codes[92]="noprotoopt"
__exit_codes[93]="protonosupport"
__exit_codes[94]="socktnosupport"
__exit_codes[95]="opnotsupp"
__exit_codes[96]="pfnosupport"
__exit_codes[97]="afnosupport"
__exit_codes[98]="addrinuse"
__exit_codes[99]="addrnotavail"
__exit_codes[100]="netdown"
__exit_codes[101]="netunreach"
__exit_codes[102]="netreset"
__exit_codes[103]="connaborted"
__exit_codes[104]="connreset"
__exit_codes[105]="nobufs"
__exit_codes[106]="isconn"
__exit_codes[107]="notconn"
__exit_codes[108]="shutdown"
__exit_codes[109]="toomanyrefs"
__exit_codes[110]="timedout"
__exit_codes[111]="connrefused"
__exit_codes[112]="hostdown"
__exit_codes[113]="hostunreach"
__exit_codes[114]="already"
__exit_codes[115]="inprogress"
__exit_codes[116]="stale"
__exit_codes[117]="uclean"
__exit_codes[118]="notnam"
__exit_codes[119]="navail"
__exit_codes[120]="isnam"
__exit_codes[121]="remoteio"
__exit_codes[122]="dquot"
__exit_codes[123]="nomedium"
__exit_codes[124]="mediumtype"
__exit_codes[125]="canceled"
__exit_codes[126]="nokey|cominv"
__exit_codes[127]="keyexpired|nocommand"
__exit_codes[128]="keyrevoked|invalexit"
__exit_codes[129]="keyrejected"


__exit_messages=()
__exit_messages[0]="Normal completion"
__exit_messages[1]="Operation not permitted | General error"
__exit_messages[2]="No such file or directory | Misuse of shell builtins"
__exit_messages[3]="No such process"
__exit_messages[4]="Interrupted system call"
__exit_messages[5]="I/O error"
__exit_messages[6]="No such device or address"
__exit_messages[7]="Argument list too long"
__exit_messages[8]="Exec format error"
__exit_messages[9]="Bad file number"
__exit_messages[10]="No child processes"
__exit_messages[11]="Try again"
__exit_messages[12]="Out of memory"
__exit_messages[13]="Permission denied"
__exit_messages[14]="Bad address"
__exit_messages[15]="Block device required"
__exit_messages[16]="Device or resource busy"
__exit_messages[17]="File exists"
__exit_messages[18]="Cross-device link"
__exit_messages[19]="No such device"
__exit_messages[20]="Not a directory"
__exit_messages[21]="Is a directory"
__exit_messages[22]="Invalid argument"
__exit_messages[23]="File table overflow"
__exit_messages[24]="Too many open files"
__exit_messages[25]="Not a typewriter"
__exit_messages[26]="Text file busy"
__exit_messages[27]="File too large"
__exit_messages[28]="No space left on device"
__exit_messages[29]="Illegal seek"
__exit_messages[30]="Read-only file system"
__exit_messages[31]="Too many links"
__exit_messages[32]="Broken pipe"
__exit_messages[33]="Math argument out of domain of func"
__exit_messages[34]="Math result not representable"
__exit_messages[35]="Resource deadlock would occur"
__exit_messages[36]="File name too long"
__exit_messages[37]="No record locks available"
__exit_messages[38]="Function not implemented"
__exit_messages[39]="Directory not empty"
__exit_messages[40]="Too many symbolic links encountered"
__exit_messages[41]="Operation would block"
__exit_messages[42]="No message of desired type"
__exit_messages[43]="Identifier removed"
__exit_messages[44]="Channel number out of range"
__exit_messages[45]="Level 2 not synchronized"
__exit_messages[46]="Level 3 halted"
__exit_messages[47]="Level 3 reset"
__exit_messages[48]="Link number out of range"
__exit_messages[49]="Protocol driver not attached"
__exit_messages[50]="No CSI structure available"
__exit_messages[51]="Level 2 halted"
__exit_messages[52]="Invalid exchange"
__exit_messages[53]="Invalid request descriptor"
__exit_messages[54]="Exchange full"
__exit_messages[55]="No anode"
__exit_messages[56]="Invalid request code"
__exit_messages[57]="Invalid slot"
__exit_messages[58]="Resource deadlock would occur"
__exit_messages[59]="Bad font file format"
__exit_messages[60]="Device not a stream"
__exit_messages[61]="No data available"
__exit_messages[62]="Timer expired"
__exit_messages[63]="Out of streams resources"
__exit_messages[64]="Machine is not on the network"
__exit_messages[65]="Package not installed"
__exit_messages[66]="Object is remote"
__exit_messages[67]="Link has been severed"
__exit_messages[68]="Advertise error"
__exit_messages[69]="Srmount error"
__exit_messages[70]="Communication error on send"
__exit_messages[71]="Protocol error"
__exit_messages[72]="Multihop attempted"
__exit_messages[73]="RFS specific error"
__exit_messages[74]="Not a data message"
__exit_messages[75]="Value too large for defined data type"
__exit_messages[76]="Name not unique on network"
__exit_messages[77]="File descriptor in bad state"
__exit_messages[78]="Remote address changed"
__exit_messages[79]="Can not access a needed shared library"
__exit_messages[80]="Accessing a corrupted shared library"
__exit_messages[81]=".lib section in a.out corrupted"
__exit_messages[82]="Attempting to link in too many shared libraries"
__exit_messages[83]="Cannot exec a shared library directly"
__exit_messages[84]="Illegal byte sequence"
__exit_messages[85]="Interrupted system call should be restarted"
__exit_messages[86]="Streams pipe error"
__exit_messages[87]="Too many users"
__exit_messages[88]="Socket operation on non-socket"
__exit_messages[89]="Destination address required"
__exit_messages[90]="Message too long"
__exit_messages[91]="Protocol wrong type for socket"
__exit_messages[92]="Protocol not available"
__exit_messages[93]="Protocol not supported"
__exit_messages[94]="Socket type not supported"
__exit_messages[95]="Operation not supported on transport endpoint"
__exit_messages[96]="Protocol family not supported"
__exit_messages[97]="Address family not supported by protocol"
__exit_messages[98]="Address already in use"
__exit_messages[99]="Cannot assign requested address"
__exit_messages[100]="Network is down"
__exit_messages[101]="Network is unreachable"
__exit_messages[102]="Network dropped connection because of reset"
__exit_messages[103]="Software caused connection abort"
__exit_messages[104]="Connection reset by peer"
__exit_messages[105]="No buffer space available"
__exit_messages[106]="Transport endpoint is already connected"
__exit_messages[107]="Transport endpoint is not connected"
__exit_messages[108]="Cannot send after transport endpoint shutdown"
__exit_messages[109]="Too many references: cannot splice"
__exit_messages[110]="Connection timed out"
__exit_messages[111]="Connection refused"
__exit_messages[112]="Host is down"
__exit_messages[113]="No route to host"
__exit_messages[114]="Operation already in progress"
__exit_messages[115]="Operation now in progress"
__exit_messages[116]="Stale NFS file handle"
__exit_messages[117]="Structure needs cleaning"
__exit_messages[118]="Not a XENIX named type file"
__exit_messages[119]="No XENIX semaphores available"
__exit_messages[120]="Is a named type file"
__exit_messages[121]="Remote I/O error"
__exit_messages[122]="Quota exceeded"
__exit_messages[123]="No medium found"
__exit_messages[124]="Wrong medium type"
__exit_messages[125]="Operation Canceled"
__exit_messages[126]="Required key not available | Command invoked cannot execute"
__exit_messages[127]="Key has expired | Command not found"
__exit_messages[128]="Key has been revoked | Invalid argument to exit"
__exit_messages[129]="Key was rejected by service"

